added printconfirm
andi34/photobooth pull request #31
Opened 2019-09-11 17:54 UTC by flighter18

did a new git clone (version 1.8.1) and added the print confirmation. 
should now work.

2019-09-11 18:39 UTC, andi34 commented
Thx :) I'll check next days. Quite busy because my GF and her daughter going to move to my apartment soon

2019-09-11 19:38 UTC, flighter18 commented
perfect thank you! And good luck :)

2019-09-16 15:39 UTC, thymon13 requested changes
correction : French translation.

2019-09-16 15:39 UTC, thymon13 commented on lang/fr.js
> +	"printing": "Imprimer commencé",
"printing": "I'impression à commencé",

2019-09-16 16:24 UTC, andi34 commented
Please keep this open until I've done a decision which way to go (swal or no swal)

2019-09-24 08:40 UTC, andi34 commented
Different solution added.
Thanks for this solution too, maybe we can use it later for other things. 🙂

2019-09-24 08:40 UTC, closed without merging