Updated Spanish translations from en file
andi34/photobooth pull request #71
Opened 2020-06-27 00:24 UTC by stroudn1

Translated en.json using a mix of what was on es.json and translating the new lines. In reference to #64 

Please let me know if I need to change anything or if you need anything else :) Thank you!!

2020-06-27 09:29 UTC, andi34 requested changes
Thanks for your contribution! I think some small parts should be changed. Not sure if I am right, see comments. I've started learning Spanish years ago but stopped with it once I was out of school... long time ago 🙈

2020-06-27 09:29 UTC, andi34 commented on resources/lang/es.json
> +  "milliseconds": "los milisegundos",
`milisegundos` should be enough If I remember right from school.

2020-06-27 09:29 UTC, andi34 commented on resources/lang/es.json
> +  "seconds": "los segundos",
Same here, `sugundo(s)`

2020-06-27 09:29 UTC, andi34 commented on resources/lang/es.json
> +  "seconds": "los segundos",
Example from countdown time inside Adminpanel:
`10 los segundos` vs `10 segundo(s)`

2020-06-28 02:22 UTC, stroudn1 commented on resources/lang/es.json
> +  "milliseconds": "los milisegundos",
Changed! I'll be submitting the updated pull request :)

2020-06-28 02:23 UTC, stroudn1 commented on resources/lang/es.json
> +  "seconds": "los segundos",
Right again :) I changed it to `segundo(s)` if that's okay

2020-06-28 02:27 UTC, stroudn1 commented
Hi @andi34 ! Looks like the new commit went through. Please let me know if anything else is needed and thank you for your input!

2020-06-29 04:56 UTC, merged

2020-06-29 04:56 UTC, andi34 commented
Thanks @stroudn1!
After https://github.com/andi34/photobooth/pull/70 there's 2 more to translate. You'd like to look at those 2 too?

2020-06-30 01:03 UTC, stroudn1 commented
@andi34 Absolutely! Can I begin translating now or should I wait?

2020-06-30 04:46 UTC, andi34 commented
Great! You could commit your changes to the `feature/qr-ssid` and create a PR for same branch, this would allow me to merge it to the main branch in one "topic".

2020-07-01 02:50 UTC, stroudn1 commented
Thank you @andi34 :) I was looking at en.json - is this where the 2 new ones are? Sorry for the confusion

2020-07-01 03:15 UTC, andi34 commented
Yeah it is. 

qrHelp was adjusted,
```
"qrHelp": "To download the picture to your smartphone, connect to the WiFi:",
```

2 new:
```
"general_wifi_ssid": "Wireless network name (SSID) used to access the photobooth",
 "manual_general_wifi_ssid": "Please define the wireless network name (SSID) to be used to access the Photobooth. The wireless network name (SSID) is displayed on the results page when the QR code is called up.",
```