Add build pipeline, improve JavaScript
andi34/photobooth pull request #90
Opened 2020-08-03 13:02 UTC by andreasremdt

Hey Andi,

I just created this new PR to prevent some merge/rebase chaos with the old one. The order of commits is the same, I just did the following changes:

* In `package.json`, there were 3 dependencies that had version numbers referenced to some GitHub repos, which prevented a successful installation on my machine. I added the latest version numbers, if you don't want this let me know.
* I installed and used the `whatwg-fetch` polyfill which should enable Safari to use the simple translator. Could you test again?

2020-08-04 03:18 UTC, andi34 requested changes
> @andi34 @andreasremdt I've tested the [whatwg-fetch](https://github.com/github/fetch) polyfill in `simple-translator` as provided in above snapshot - works great on iOS 9 / iPad2, thanks a million.
> 
> I found one more small thing to be adjusted, in order to make it work with Photobooth on iPad2.
> 
> There seems to be an [Javascript ES6 TypeError in Safari & IE](https://stackoverflow.com/questions/45971119/javascript-es6-typeerror-in-safari-ie) when iterating over a NodeList object using `forEach`. Along that comment, I tried the following change in the `simple-translator`code-base, file `translate.js`, member function `translatePageTo`:
> 
> ```
> <                     elements.forEach(function(element) {
> ---
> >                     Array.from(elements).forEach(function(element) {
> ```
> 
> which then made Photobooth translations work perfectly well on iPad2.
> 
> I tried to provide a simple PR but was not able to find the repo / branch where the backward compatible code base resides which is included in the snapshot (i.e. no more use of arrow function). If you are ok to take it from here would be great or let me know where to look and I am happy to provide a PR for this change.
> 
> Once more thanks for all the support and your willingness to go beyond, and to make it work.

2020-08-04 13:13 UTC, andreasremdt commented
I just added Prettier to have consistent formatting for both JavaScript & SCSS. If you don't like the formatting (for example the 80 characters max-width which I could understand) let me know, we can still tweak the settings.

2020-08-05 03:21 UTC, andi34 commented on login/index.php
> +	<script src="node_modules/whatwg-fetch/dist/fetch.umd.js"></script>
../node_modules/

2020-08-05 03:24 UTC, andi34 requested changes
I'll fix that later today

2020-08-05 03:24 UTC, andi34 commented on manual/index.php
> +	<script src="node_modules/whatwg-fetch/dist/fetch.umd.js"></script>
../node_modules/

2020-08-05 03:24 UTC, andi34 commented on login/index.php
> +	<script src="node_modules/whatwg-fetch/dist/fetch.umd.js"></script>
../node_modules/

2020-08-05 03:24 UTC, andi34 commented on slideshow/index.php
../node_modules/

2020-08-05 03:24 UTC, andi34 commented on admin/index.php
> +	<script src="node_modules/whatwg-fetch/dist/fetch.umd.js"></script>
../node_modules/

2020-08-05 18:14 UTC, andi34 commented
rebased on dev branch. will merge once i get feedback :)

2020-08-05 18:41 UTC, andi34 approved these changes

2020-08-06 18:00 UTC, merged

2020-08-08 20:35 UTC, andi34 commented
.